#!/bin/bash

function run {
cmd="qdbus org.kde.yakuake $1"
eval $cmd &> /dev/null
sleep 0.5
}

# Home tab
run "/yakuake/sessions org.kde.yakuake.addSession"
run "/yakuake/tabs org.kde.yakuake.setTabTitle 0 'Home'"

# Running tab (with `htop` running)
run "/yakuake/sessions org.kde.yakuake.addSession"
run "/yakuake/tabs org.kde.yakuake.setTabTitle 1 'Running'"
run "/yakuake/sessions runCommandInTerminal 1 'htop'"

# Env tab (for projects)
run "/yakuake/sessions org.kde.yakuake.addSession"
run "/yakuake/tabs org.kde.yakuake.setTabTitle 2 'Env'"
run "/yakuake/sessions org.kde.yakuake.splitSessionLeftRight 2"

# Misc shell
run "/yakuake/tabs org.kde.yakuake.setTabTitle 3 'Misc'"
run "/yakuake/sessions runCommandInTerminal 3 'emacs --daemon'"
