autoload -U colors && colors

setopt autocd		# Automatically cd into typed directory.
stty stop undef		# Disable ctrl-s to freeze terminal.

# History in cache directory:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/history

# Load aliases and shortcuts if existent.
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc"

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

# Load syntax highlighting; should be last.
source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh 2>/dev/null

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export NVIM_CONFIG=$HOME/.config/nvim/init.vim
alias nvimrc="v $NVIM_CONFIG"

export ZSH_CONFIG=$HOME/.config/zsh/.zshrc
alias zshrc="v $ZSH_CONFIG"

# # Save the current dir into the .shell_local file for later access
# alias save_pwd='echo $PWD >> ~/.shell_local'
# # Runs before every shell execution
# preexec() {
#     save_pwd
# }
# # Return to a previous shell location
# alias cz='cd $(tail -1000 ~/.shell_local | sort - | uniq | fzf)'

export PATH="$PATH:$HOME/bin"

export BROWSER="brave"

source $HOME/.cargo/env
source $HOME/.config/broot/launcher/bash/br

eval "$(starship init zsh)"

source /home/conor/.config/broot/launcher/bash/br
